import 'package:flutter/material.dart';
import 'package:study_language_ai_flutter_project/common/const/enums.dart';

const BLUE_COLOR = Color(0xFF007AFF);
const GREEN_COLOR = Color(0xFF34C759);
const YELLOW_COLOR = Color(0xFFFFD740);

const initial_Directory = 'all';

const card_box_name = 'userBox';

const login_saved_email_key = 'login_email';
const base_lang_key = 'BaseLang';
const tolang_save_key = 'toLang';
const upload_star_card_box = 'userChoice';

const coin_padding = 8.0;

const Map<String, String> MlKitPossibleLangMap = {
  'af': 'Afrikaans',
  'am': 'Amharic',
  'ar': 'Arabic',
  'ar-Latn': 'Arabic',
  'az': 'Azerbaijani',
  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bg-Latn': 'Bulgarian',
  'bn': 'Bengali',
  'bs': 'Bosnian',
  'ca': 'Catalan',
  'ceb': 'Cebuano',
  'co': 'Corsican',
  'cs': 'Czech',
  'cy': 'Welsh',
  'da': 'Danish',
  'de': 'German',
  'el': 'Greek',
  'el-Latn': 'Greek',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Spanish',
  'et': 'Estonian',
  'eu': 'Basque',
  'fa': 'Persian',
  'fi': 'Finnish',
  'fil': 'Filipino',
  'fr': 'French',
  'fy': 'Frisian', // 원형 : Western Frisian
  'ga': 'Irish',
  'gd': 'ScottishGaelic', //Scots Gaelic
  'gl': 'Galician',
  'gu': 'Gujarati',
  'ha': 'Hausa',
  'haw': 'Hawaiian',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hi-Latn': 'Hindi',
  'hmn': 'Hmong',
  'hr': 'Croatian',
  'ht': 'HaitianCreole', // Haitian
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'id': 'Indonesian',
  'ig': 'Igbo',
  'is': 'Icelandic',
  'it': 'Italian',
  'ja': 'Japanese',
  'ja-Latn': 'Japanese',
  'jv': 'Javanese',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'ku': 'Kurdish',
  'ky': 'Kyrgyz',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'mg': 'Malagasy',
  'mi': 'Maori',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',
  'my': 'BurmeseMyanmar', //Burmese
  'ne': 'Nepali',
  'nl': 'Dutch',
  'no': 'Norwegian',
  'ny': 'Nyanja',
  'pa': 'Punjabi',
  'pl': 'Polish',
  'ps': 'Pashto',
  'pt': 'Portuguese',
  'ro': 'Romanian',
  'ru': 'Russian',
  'ru-Latn': 'Russian',
  'sd': 'Sindhi',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'sm': 'Samoan',
  'sn': 'Shona',
  'so': 'Somali',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'st': 'Sesotho',
  'su': 'Sundanese',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'th': 'Thai',
  'tr': 'Turkish',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'vi': 'Vietnamese',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'zh': 'Chinese',
  'zh-Latn': 'Chinese',
  'zu': 'Zulu',
  'und' : 'Unknown',
};

const Map<String, String> VoiceAudioToLangMap =  {
  'Afrikaans (South Africa)': 'Afrikaans',
  'Arabic': 'Arabic',
  'Basque (Spain)': 'Basque',
  'Bengali (India)': 'Bengali',
  'Bulgarian (Bulgaria)': 'Bulgarian',
  'Catalan (Spain)': 'Catalan',
  'Chinese (Hong Kong)': 'Chinese',
  'Czech (Czech Republic)': 'Czech',
  'Danish (Denmark)': 'Danish',
  'Dutch (Belgium)': 'Dutch',
  'Dutch (Netherlands)': 'Dutch',
  'English (Australia)': 'English',
  'English (India)': 'English',
  'English (UK)': 'English',
  'English (US)': 'English',
  'Filipino (Philippines)': 'Filipino',
  'Finnish (Finland)': 'Finnish',
  'French (Canada)': 'French',
  'French (France)': 'French',
  'Galician (Spain)': 'Galician',
  'German (Germany)': 'German',
  'Greek (Greece)': 'Greek',
  'Gujarati (India)': 'Gujarati',
  'Hebrew (Israel)': 'Hebrew',
  'Hindi (India)': 'Hindi',
  'Hungarian (Hungary)': 'Hungarian',
  'Icelandic (Iceland)': 'Icelandic',
  'Indonesian (Indonesia)': 'Indonesian',
  'Italian (Italy)': 'Italian',
  'Japanese (Japan)': 'Japanese',
  'Kannada (India)': 'Kannada',
  'Korean (South Korea)': 'Korean',
  'Latvian (Latvia)': 'Latvian',
  'Lithuanian (Lithuania)': 'Lithuanian',
  'Malay (Malaysia)': 'Malay',
  'Malayalam (India)': 'Malayalam',
  'Mandarin Chinese': 'Chinese',
  'Marathi (India)': 'Marathi',
  'Norwegian (Norway)': 'Norwegian',
  'Polish (Poland)': 'Polish',
  'Portuguese (Brazil)': 'Portuguese',
  'Portuguese (Portugal)': 'Portuguese',
  'Punjabi (India)': 'Punjabi',
  'Romanian (Romania)': 'Romanian',
  'Russian (Russia)': 'Russian',
  'Serbian (Cyrillic)': 'Serbian',
  'Slovak (Slovakia)': 'Slovak',
  'Spanish (Spain)': 'Spanish',
  'Spanish (US)': 'Spanish',
  'Swedish (Sweden)': 'Swedish',
  'Tamil (India)': 'Tamil',
  'Telugu (India)': 'Telugu',
  'Thai (Thailand)': 'Thai',
  'Turkish (Turkey)': 'Turkish',
  'Ukrainian (Ukraine)': 'Ukrainian',
  'Vietnamese (Vietnam)': 'Vietnamese'
};

const VoiceAudioLangToCode = {'Afrikaans (South Africa)': 'af-ZA',
'Arabic': 'ar-XA',
'Basque (Spain)': 'eu-ES',
'Bengali (India)': 'bn-IN',
'Bulgarian (Bulgaria)': 'bg-BG',
'Catalan (Spain)': 'ca-ES',
'Chinese (Hong Kong)': 'yue-HK',
'Czech (Czech Republic)': 'cs-CZ',
'Danish (Denmark)': 'da-DK',
'Dutch (Belgium)': 'nl-BE',
'Dutch (Netherlands)': 'nl-NL',
'English (Australia)': 'en-AU',
'English (India)': 'en-IN',
'English (UK)': 'en-GB',
'English (US)': 'en-US',
'Filipino (Philippines)': 'fil-PH',
'Finnish (Finland)': 'fi-FI',
'French (Canada)': 'fr-CA',
'French (France)': 'fr-FR',
'Galician (Spain)': 'gl-ES',
'German (Germany)': 'de-DE',
'Greek (Greece)': 'el-GR',
'Gujarati (India)': 'gu-IN',
'Hebrew (Israel)': 'he-IL',
'Hindi (India)': 'hi-IN',
'Hungarian (Hungary)': 'hu-HU',
'Icelandic (Iceland)': 'is-IS',
'Indonesian (Indonesia)': 'id-ID',
'Italian (Italy)': 'it-IT',
'Japanese (Japan)': 'ja-JP',
'Kannada (India)': 'kn-IN',
'Korean (South Korea)': 'ko-KR',
'Latvian (Latvia)': 'lv-LV',
'Lithuanian (Lithuania)': 'lt-LT',
'Malay (Malaysia)': 'ms-MY',
'Malayalam (India)': 'ml-IN',
'Mandarin Chinese': 'cmn-TW',
'Marathi (India)': 'mr-IN',
'Norwegian (Norway)': 'nb-NO',
'Polish (Poland)': 'pl-PL',
'Portuguese (Brazil)': 'pt-BR',
'Portuguese (Portugal)': 'pt-PT',
'Punjabi (India)': 'pa-IN',
'Romanian (Romania)': 'ro-RO',
'Russian (Russia)': 'ru-RU',
'Serbian (Cyrillic)': 'sr-RS',
'Slovak (Slovakia)': 'sk-SK',
'Spanish (Spain)': 'es-ES',
'Spanish (US)': 'es-US',
'Swedish (Sweden)': 'sv-SE',
'Tamil (India)': 'ta-IN',
'Telugu (India)': 'te-IN',
'Thai (Thailand)': 'th-TH',
'Turkish (Turkey)': 'tr-TR',
'Ukrainian (Ukraine)': 'uk-UA',
'Vietnamese (Vietnam)': 'vi-VN'};

Map<Lang, Color> langColors = {
  Lang.Afrikaans: Color(0xFFE63946),
  Lang.Albanian: Color(0xFF1D3557),
  Lang.Amharic: Color(0xFFA8DADC),
  Lang.Arabic: Color(0xFF457B9D),
  Lang.Armenian: Color(0xFFF4A261),
  Lang.Assamese: Color(0xFF2A9D8F),
  Lang.Aymara: Color(0xFFB5838D),
  Lang.Azerbaijani: Color(0xFF6D597A),
  Lang.Bambara: Color(0xFF5B5F97),
  Lang.Basque: Color(0xFF355C7D),
  Lang.Belarusian: Color(0xFF6C757D),
  Lang.Bengali: Color(0xFF03A9F4),
  Lang.Bhojpuri: Color(0xFFE91E63),
  Lang.Bosnian: Color(0xFF4CAF50),
  Lang.Bulgarian: Color(0xFF607D8B),
  Lang.BurmeseMyanmar: Color(0xFF9C27B0),
  Lang.Catalan: Color(0xFF7CB342),
  Lang.Cebuano: Color(0xFF795548),
  Lang.Chewa: Color(0xFFF0E68C),
  Lang.Chinese: Color(0xFF8A2BE2),
  Lang.ChineseSimplified: Color(0xFF7FFF00),
  Lang.ChineseTraditional: Color(0xFFD2691E),
  Lang.Chonga: Color(0xFFFF4500),
  Lang.Corsican: Color(0xFF2E8B57),
  Lang.Creole: Color(0xFFADFF2F),
  Lang.Croatian: Color(0xFF00FFFF),
  Lang.Czech: Color(0xFFBDB76B),
  Lang.Danish: Color(0xFF8B008B),
  Lang.Divehi: Color(0xFF9400D3),
  Lang.Dogri: Color(0xFF1E90FF),
  Lang.Dutch: Color(0xFFB22222),
  Lang.English: Color(0xFFFF6347),
  Lang.Esperanto: Color(0xFF7FFF00),
  Lang.Estonian: Color(0xFFDAA520),
  Lang.Ewe: Color(0xFF9ACD32),
  Lang.Filipino: Color(0xFFFF69B4),
  Lang.Finnish: Color(0xFF4B0082),
  Lang.French: Color(0xFFFFD700),
  Lang.Frisian: Color(0xFFF8F8FF),
  Lang.Galician: Color(0xFFD8BFD8),
  Lang.Georgian: Color(0xFF006400),
  Lang.German: Color(0xFFBDB76B),
  Lang.Greek: Color(0xFFFF4500),
  Lang.Guarani: Color(0xFF2E8B57),
  Lang.Gujarati: Color(0xFFDAA520),
  Lang.HaitianCreole: Color(0xFF9ACD32),
  Lang.Hausa: Color(0xFFFFD700),
  Lang.Hawaiian: Color(0xFF20B2AA),
  Lang.Hebrew: Color(0xFFFF00FF),
  Lang.Hindi: Color(0xFFADFF2F),
  Lang.Hmong: Color(0xFF00FFFF),
  Lang.Hungarian: Color(0xFFFF6347),
  Lang.Icelandic: Color(0xFF7FFF00),
  Lang.Igbo: Color(0xFFD2691E),
  Lang.Ilocano: Color(0xFF8B0000),
  Lang.Indonesian: Color(0xFFBDB76B),
  Lang.Irish: Color(0xFF013220),
  Lang.Italian: Color(0xFF228B22),
  Lang.Japanese: Color(0xFFFF00FF),
  Lang.Javanese: Color(0xFFFFD700),
  Lang.Kannada: Color(0xFFADFF2F),
  Lang.Kazakh: Color(0xFF8A2BE2),
  Lang.Khmer: Color(0xFFA52A2A),
  Lang.Kinyarwanda: Color(0xFFDEB887),
  Lang.Konkani: Color(0xFF5F9EA0),
  Lang.Korean: Color(0xFF7FFF00),
  Lang.Kurdish: Color(0xFFD2691E),
  Lang.Kyrgyz: Color(0xFFFFE4C4),
  Lang.Lao: Color(0xFF8A2BE2),
  Lang.Latin: Color(0xFF7FFF00),
  Lang.Latvian: Color(0xFFDAA520),
  Lang.Lingala: Color(0xFF9ACD32),
  Lang.Lithuanian: Color(0xFF556B2F),
  Lang.Luganda: Color(0xFFCD5C5C),
  Lang.Luxembourgish: Color(0xFFF08080),
  Lang.Macedonian: Color(0xFFE9967A),
  Lang.Maithili: Color(0xFFFA8072),
  Lang.Malagasy: Color(0xFFFFA07A),
  Lang.Malay: Color(0xFFDC143C),
  Lang.Malayalam: Color(0xFFFF0000),
  Lang.Maltese: Color(0xFFBC8F8F),
  Lang.Maori: Color(0xFF4169E1),
  Lang.Marathi: Color(0xFF8A2BE2),
  Lang.MeiteiManipuri: Color(0xFF7B68EE),
  Lang.Mizo: Color(0xFF6A5ACD),
  Lang.Mongolian: Color(0xFF483D8B),
  Lang.Nepali: Color(0xFF2E8B57),
  Lang.NorthernSotho: Color(0xFF00CED1),
  Lang.Norwegian: Color(0xFF9400D3),
  Lang.Nyanja: Color(0xFFFF00FF),
  Lang.Oriya: Color(0xFFFF00FF),
  Lang.Oromo: Color(0xFF8A2BE2),
  Lang.Pashto: Color(0xFFA52A2A),
  Lang.Persian: Color(0xFF7FFF00),
  Lang.Polish: Color(0xFF7FFF00),
  Lang.Portuguese: Color(0xFFDAA520),
  Lang.Punjabi: Color(0xFF9ACD32),
  Lang.Quechua: Color(0xFFFFD700),
  Lang.Romanian: Color(0xFF5F9EA0),
  Lang.Russian: Color(0xFF7FFF00),
  Lang.Samoan: Color(0xFFFF69B4),
  Lang.ScottishGaelic: Color(0xFF4B0082),
  Lang.Serbian: Color(0xFFFFD700),
  Lang.Sesotho: Color(0xFFF8F8FF),
  Lang.Shona: Color(0xFFFF00FF),
  Lang.Sindhi: Color(0xFFADFF2F),
  Lang.Sinhala: Color(0xFF20B2AA),
  Lang.Slovak: Color(0xFF00CED1),
  Lang.Slovenian: Color(0xFF9400D3),
  Lang.Somali: Color(0xFFFF00FF),
  Lang.Spanish: Color(0xFFFF0000),
  Lang.Sundanese: Color(0xFFBC8F8F),
  Lang.Swahili: Color(0xFF4169E1),
  Lang.Swedish: Color(0xFF8A2BE2),
  Lang.Sanskrit: Color(0xFF7B68EE),
  Lang.Tajik: Color(0xFF2E8B57),
  Lang.Tamil: Color(0xFF00CED1),
  Lang.Tatar: Color(0xFF9400D3),
  Lang.Telugu: Color(0xFFFF00FF),
  Lang.Thai: Color(0xFF8A2BE2),
  Lang.Tigrinya: Color(0xFF7FFF00),
  Lang.Twi: Color(0xFF9ACD32),
  Lang.Turkish: Color(0xFF556B2F),
  Lang.Turkmen: Color(0xFFCD5C5C),
  Lang.Ukrainian: Color(0xFFF08080),
  Lang.Urdu: Color(0xFFE9967A),
  Lang.Uzbek: Color(0xFFFA8072),
  Lang.Vietnamese: Color(0xFFFFA07A),
  Lang.Welsh: Color(0xFFDC143C),
  Lang.Xhosa: Color(0xFFBC8F8F),
  Lang.Yiddish: Color(0xFF4169E1),
  Lang.Yoruba: Color(0xFF8A2BE2),
  Lang.Zulu: Color(0xFF7B68EE),
  Lang.Unknown: Color(0xFFBDBDBD),
};