
import 'package:hive/hive.dart';

part 'enums.g.dart';

@HiveType(typeId: 3)
enum Lang {
  @HiveField(0)
  Afrikaans,
  @HiveField(1)
  Albanian,
  @HiveField(2)
  Amharic,
  @HiveField(3)
  Arabic,
  @HiveField(4)
  Armenian,
  @HiveField(5)
  Assamese,
  @HiveField(6)
  Aymara,
  @HiveField(7)
  Azerbaijani,
  @HiveField(8)
  Bambara,
  @HiveField(9)
  Basque,
  @HiveField(10)
  Belarusian,
  @HiveField(11)
  Bengali,
  @HiveField(12)
  Bhojpuri,
  @HiveField(13)
  Bosnian,
  @HiveField(14)
  Bulgarian,
  @HiveField(15)
  BurmeseMyanmar,
  @HiveField(16)
  Catalan,
  @HiveField(17)
  Cebuano,
  @HiveField(18)
  Chewa,
  @HiveField(19)
  Chinese,
  @HiveField(20)
  ChineseSimplified,
  @HiveField(21)
  ChineseTraditional,
  @HiveField(22)
  Chonga,
  @HiveField(23)
  Corsican,
  @HiveField(24)
  Creole,
  @HiveField(25)
  Croatian,
  @HiveField(26)
  Czech,
  @HiveField(27)
  Danish,
  @HiveField(28)
  Divehi,
  @HiveField(29)
  Dogri,
  @HiveField(30)
  Dutch,
  @HiveField(31)
  English,
  @HiveField(32)
  Esperanto,
  @HiveField(33)
  Estonian,
  @HiveField(34)
  Ewe,
  @HiveField(35)
  Filipino,
  @HiveField(36)
  Finnish,
  @HiveField(37)
  French,
  @HiveField(38)
  Frisian,
  @HiveField(39)
  Galician,
  @HiveField(40)
  Georgian,
  @HiveField(41)
  German,
  @HiveField(42)
  Greek,
  @HiveField(43)
  Guarani,
  @HiveField(44)
  Gujarati,
  @HiveField(45)
  HaitianCreole,
  @HiveField(46)
  Hausa,
  @HiveField(47)
  Hawaiian,
  @HiveField(48)
  Hebrew,
  @HiveField(49)
  Hindi,
  @HiveField(50)
  Hmong,
  @HiveField(51)
  Hungarian,
  @HiveField(52)
  Icelandic,
  @HiveField(53)
  Igbo,
  @HiveField(54)
  Ilocano,
  @HiveField(55)
  Indonesian,
  @HiveField(56)
  Irish,
  @HiveField(57)
  Italian,
  @HiveField(58)
  Japanese,
  @HiveField(59)
  Javanese,
  @HiveField(60)
  Kannada,
  @HiveField(61)
  Kazakh,
  @HiveField(62)
  Khmer,
  @HiveField(63)
  Kinyarwanda,
  @HiveField(64)
  Konkani,
  @HiveField(65)
  Korean,
  @HiveField(66)
  Kurdish,
  @HiveField(67)
  Kyrgyz,
  @HiveField(68)
  Lao,
  @HiveField(69)
  Latin,
  @HiveField(70)
  Latvian,
  @HiveField(71)
  Lingala,
  @HiveField(72)
  Lithuanian,
  @HiveField(73)
  Luganda,
  @HiveField(74)
  Luxembourgish,
  @HiveField(75)
  Macedonian,
  @HiveField(76)
  Maithili,
  @HiveField(77)
  Malagasy,
  @HiveField(78)
  Malay,
  @HiveField(79)
  Malayalam,
  @HiveField(80)
  Maltese,
  @HiveField(81)
  Maori,
  @HiveField(82)
  Marathi,
  @HiveField(83)
  MeiteiManipuri,
  @HiveField(84)
  Mizo,
  @HiveField(85)
  Mongolian,
  @HiveField(86)
  Nepali,
  @HiveField(87)
  NorthernSotho,
  @HiveField(88)
  Norwegian,
  @HiveField(89)
  Nyanja,
  @HiveField(90)
  Oriya,
  @HiveField(91)
  Oromo,
  @HiveField(92)
  Pashto,
  @HiveField(93)
  Persian,
  @HiveField(94)
  Polish,
  @HiveField(95)
  Portuguese,
  @HiveField(96)
  Punjabi,
  @HiveField(97)
  Quechua,
  @HiveField(98)
  Romanian,
  @HiveField(99)
  Russian,
  @HiveField(100)
  Samoan,
  @HiveField(101)
  Sanskrit,
  @HiveField(102)
  ScottishGaelic,
  @HiveField(103)
  Serbian,
  @HiveField(104)
  Sesotho,
  @HiveField(105)
  Shona,
  @HiveField(106)
  Sindhi,
  @HiveField(107)
  Sinhala,
  @HiveField(108)
  Slovak,
  @HiveField(109)
  Slovenian,
  @HiveField(110)
  Somali,
  @HiveField(111)
  Spanish,
  @HiveField(112)
  Sundanese,
  @HiveField(113)
  Swahili,
  @HiveField(114)
  Swedish,
  @HiveField(115)
  Tajik,
  @HiveField(116)
  Tamil,
  @HiveField(117)
  Tatar,
  @HiveField(118)
  Telugu,
  @HiveField(119)
  Thai,
  @HiveField(120)
  Tigrinya,
  @HiveField(121)
  Turkish,
  @HiveField(122)
  Turkmen,
  @HiveField(123)
  Twi,
  @HiveField(124)
  Ukrainian,
  @HiveField(125)
  Urdu,
  @HiveField(126)
  Uyghur,
  @HiveField(127)
  Uzbek,
  @HiveField(128)
  Vietnamese,
  @HiveField(129)
  Welsh,
  @HiveField(130)
  Xhosa,
  @HiveField(131)
  Yiddish,
  @HiveField(132)
  Yoruba,
  @HiveField(133)
  Zulu,
  @HiveField(134)
  Unknown,
}
